const actionTypes = {
    SEARCH_ARTIST: "SEARCH_ARTIST",
    CLEAR_RESULTS: "CLEAR_RESULTS",
    NEXT_RESULTS: "NEXT_RESULTS",
    PREVIOUS_RESULTS: "PREVIOUS_RESULTS",
    SHOW_ALBUM_INFO: "SHOW_ALBUM_INFO",
    SEARCH_ARTIST2_SUCCESS: "SEARCH_ARTIST2_SUCCESS"
};

export default actionTypes